### PR TITLE
Make HIST_STAMPS works and add color to history

### LINKED ISSUE #233: Changing date format to dd.mm.yyyy break history command.
After changing the date format o dd.mm.yyyy, I start getting the following error message when I try to execute `history`

`bash: fc: -E: invalid option`

Steps to reproduce.

1 - Change the date format in bashrc: to dd.mm.yyyy
`HIST_STAMPS="dd.mm.yyyy"`

2 - Uncomment the line below in $OSH/lib/history.sh

```
case $HIST_STAMPS in
  #"mm/dd/yyyy") alias history='fc -fl 1' ;;
  "dd.mm.yyyy") alias history='fc -El 1' ;;
  #"yyyy-mm-dd") alias history='fc -il 1' ;;
  *) alias history='fc -l 1' ;;
esac

```

3 - Run the` history` command.

### PR DESCRIPTION
**Pull request by jvitorinoj**
Make HIST_STAMPS works
fix #233 

add color to the timestamp field in history
history

### CODE REVIEW

File: lib/history.sh [hunk 1]
```diff
@@ -51,10 +46,14 @@ bind '"\e[B": history-search-forward'
...
-  #"mm/dd/yyyy") alias history='fc -fl 1' ;;
-  #"dd.mm.yyyy") alias history='fc -El 1' ;;
-  #"yyyy-mm-dd") alias history='fc -il 1' ;;
-  #*) alias history='fc -l 1' ;;
-#esac
+case $HIST_STAMPS in
+  "mm/dd/yyyy") HISTTIMEFORMAT=$(echo -e '\033[31m[%m/%d/%Y] \033[36m[%T]\033[0m ');;
+  "dd.mm.yyyy") HISTTIMEFORMAT=$(echo -e '\033[31m [%d.%m.%Y] \033[36m[%T]\033[0m ') ;;
+  "yyyy-mm-dd") HISTTIMEFORMAT=$(echo -e '\033[31m%Y-%m-%d] \033[36m[%T]\033[0m ') ;;
+  *) HISTTIMEFORMAT=$(echo -e '\033[31m%F \033[36m%T\033[0m ') ;;
```
Comment (akinomyoga) [inline lib/history.sh:58]: You don't have to make subshells (which are slow) to expand escape sequences. Instead you can use `$'...'`.

```suggestion
  "mm/dd/yyyy") HISTTIMEFORMAT=$'\033[31m[%m/%d/%Y] \033[36m[%T]\033[0m ' ;;
  "dd.mm.yyyy") HISTTIMEFORMAT=$'\033[31m [%d.%m.%Y] \033[36m[%T]\033[0m ' ;;
  "yyyy-mm-dd") HISTTIMEFORMAT=$'\033[31m%Y-%m-%d] \033[36m[%T]\033[0m ' ;;
  *) HISTTIMEFORMAT=$'\033[31m%F \033[36m%T\033[0m ' ;;
```

File: lib/history.sh [hunk 2]
```diff
@@ -51,10 +46,14 @@ bind '"\e[B": history-search-forward'
...
-#case $HIST_STAMPS in
-  #"mm/dd/yyyy") alias history='fc -fl 1' ;;
-  #"dd.mm.yyyy") alias history='fc -El 1' ;;
-  #"yyyy-mm-dd") alias history='fc -il 1' ;;
-  #*) alias history='fc -l 1' ;;
-#esac
+case $HIST_STAMPS in
+  "mm/dd/yyyy") HISTTIMEFORMAT=$'\033[31m[%m/%d/%Y] \033[36m[%T]\033[0m ' ;;
+  "dd.mm.yyyy") HISTTIMEFORMAT=$'\033[31m [%d.%m.%Y] \033[36m[%T]\033[0m ' ;;
+  "yyyy-mm-dd") HISTTIMEFORMAT=$'\033[31m%Y-%m-%d] \033[36m[%T]\033[0m ' ;;
```
Comment (akinomyoga) [inline lib/history.sh:57]:
```suggestion
  "yyyy-mm-dd") HISTTIMEFORMAT=$'\033[31m[%F] \033[36m[%T]\033[0m ' ;;
```

File: lib/history.sh [hunk 3]
```diff
@@ -51,10 +46,14 @@ bind '"\e[B": history-search-forward'
...
 # Show history
-#case $HIST_STAMPS in
-  #"mm/dd/yyyy") alias history='fc -fl 1' ;;
-  #"dd.mm.yyyy") alias history='fc -El 1' ;;
-  #"yyyy-mm-dd") alias history='fc -il 1' ;;
-  #*) alias history='fc -l 1' ;;
-#esac
+case $HIST_STAMPS in
+  "mm/dd/yyyy") HISTTIMEFORMAT=$'\033[31m[%m/%d/%Y] \033[36m[%T]\033[0m ' ;;
+  "dd.mm.yyyy") HISTTIMEFORMAT=$'\033[31m [%d.%m.%Y] \033[36m[%T]\033[0m ' ;;
```
Comment (akinomyoga) [inline lib/history.sh:56]: Is there a reason for a space here?

```suggestion
  "dd.mm.yyyy") HISTTIMEFORMAT=$'\033[31m[%d.%m.%Y] \033[36m[%T]\033[0m ' ;;
```

File: templates/bashrc.osh-template [hunk 4]
```diff
@@ -38,7 +38,8 @@ OSH_THEME="font"
 # Uncomment the following line if you want to change the command execution time
 # stamp shown in the history command output.
 # The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
-# HIST_STAMPS="mm/dd/yyyy"
+# IF not set, default value is: yyyy-mm-dd
+# HIST_STAMPS="yyyy-mm-dd"
```
Comment (akinomyoga) [inline templates/bashrc.osh-template:42]: The default behavior seems to be slightly different from `yyyy-mm-dd`, i.e., there is no brackets `[...]` around the date and time.

**Review by akinomyoga — COMMENTED** [review]
I'm thinking of merging this, but there are a few questions or suggestions.

File: templates/bashrc.osh-template (hunk 4 above)
Comment (akinomyoga) [reply templates/bashrc.osh-template]: d830c75 I decided to change not to enclose the date and time within [...] by default. Instead, I have added new possible format names as `[mm/dd/yyyy]`, `[dd.mm.yyyy]`, and `[yyyy-mm-dd]`. Also, the colors are only enabled with the formats with `[]`.

**Review by akinomyoga — DISMISSED** [review]
Additionally, I have removed the trailing spaces fcbb3fb. I will keep this open for about a week and merge it if there are no problems or comments.

**Review by akinomyoga — APPROVED** [review]
> Additionally, I have removed the trailing spaces [fcbb3fb](https://github.com/ohmybash/oh-my-bash/commit/fcbb3fb5123cd55218e534de7373d8e0ba4e5e28).

Ah! Now I noticed that this is already suggested in #191, so dropped it. Sorry for the noise!

**Comment by akinomyoga** [comment]
I have merged it. Thank you for your contribution!
