### PR TITLE
oh-my-bash.sh : Fix for #70 #59

### LINKED ISSUE #59: Problem with agnoster theme.
Making agnoster as default theme, the terminal displays a message saying "No such file of directory" for the file agnoster.theme.sh. When I looked into the directory, their is a file named agnoster-bash.theme.sh

### LINKED ISSUE #70: OSH_THEME=agnoster -> No such file or directory
`OSH_THEME=agnoster` results in `bash: /home/kreyren/.oh-my-bash/themes/agnoster/agnoster.theme.sh` since filename is `agnoster/agnoster-bash.theme.sh`

### PR DESCRIPTION
**Pull request by Kreyren**
Fixes #70 
Fixes #59

### CODE REVIEW

File: oh-my-bash.sh [hunk 1]
```diff
@@ -144,6 +144,9 @@ else
       source "$OSH_CUSTOM/$OSH_THEME/$OSH_THEME.theme.sh"
     elif [ -f "$OSH_CUSTOM/themes/$OSH_THEME/$OSH_THEME.theme.sh" ]; then
       source "$OSH_CUSTOM/themes/$OSH_THEME/$OSH_THEME.theme.sh"
+		# https://github.com/ohmybash/oh-my-bash/issues/70
```
Comment (nntoan) [inline oh-my-bash.sh]: @Kreyren I prefer we keep only one naming convention for the theme or plugins. If agnoster theme file name is `agnostic-bash.theme.sh`, then we should refactor it to match with `$OSH_THEME`.theme.sh.

Cheers,
Toan

Comment (Kreyren) [reply oh-my-bash.sh]: Fixed in https://github.com/ohmybash/oh-my-bash/pull/71/commits/fb6e15a38a079597787bae2644efe025f5a90029
